root: ./

structure:
  readme: README.md
  summary: SUMMARY.md

redirects:
  about: ./about/README.md
  product: ./product/README.md
  collectives: ./collectives/README.md
  backers-and-sponsors: ./financial-contributors/financial-contributors.md
  backers-and-sponsors/sponsor-faq: ./financial-contributors/organizations/README.md
  backers-and-sponsors/payment: ./financial-contributors/payments.md
  backers-and-sponsors/collective-to-collective-donations: ./financial-contributors/collectives/collective-to-collective-donations.md
  backers-and-sponsors/gift-cards: ./financial-contributors/organizations/gift-cards.md
  backers-and-sponsors/bulk-transfers: ./financial-contributors/organizations/bulk-transfers.md
  backers-and-sponsors/website-badge: ./financial-contributors/website-badge.md
  backers-and-sponsors/sustainer-resources: ./financial-contributors/organizations/sustainer-resources.md
  expenses: ./expenses/README.md
  hosts: ./fiscal-hosts/fiscal-hosts.md
  hosts/become-host: ./fiscal-hosts/become-a-fiscal-host.md
  hosts/create-a-fiscal-host: ./fiscal-hosts/create-a-fiscal-host.md
  hosts/fiscal-host-settings: ./fiscal-hosts/fiscal-host-settings.md
  hosts/invoices: ./fiscal-hosts/invoices.md
  hosts/payouts: ./fiscal-hosts/payouts.md
  hosts/host-dashboard: ./fiscal-hosts/fiscal-host-dashboard.md
  hosts/add-funds-manually: ./fiscal-hosts/add-funds-manually.md
  hosts/refunds: ./fiscal-hosts/refunds.md
  hosts/host-fees: ./fiscal-hosts/fiscal-hosts-fees.md
  hosts/local-tax: ./fiscal-hosts/local-tax.md
  hosts/sponsor-agreement: ./fiscal-hosts/sponsor-agreement.md
  hosts/open-source-collective: ./fiscal-hosts/open-source-collective.md
  developers: ./contributing/development/README.md
  developers/dev-contribution-guide: ./contributing/development/dev-contribution-guide.md
  developers/guidelines: ./contributing/development/best-practice-guidelines.md
  developers/bounties: ./contributing/development/bounties.md
  developers/api: ./contributing/development/api/README.md
  developers/api/members: ./contributing/development/api/members.md
  developers/api/users-emails: ./contributing/development/api/users-emails.md
  developers/api/collectives: ./contributing/development/api/collectives.md
  developers/api/events: ./contributing/development/api/events.md
  developers/readme-integration: ./contributing/development/readme-integration.md
  developers/architecture: ./contributing/development/architecture.md
  developers/postgres-database: ./contributing/development/postgres-database.md
  developers/paypal: ./contributing/development/paypal.md
  developers/transferwise: ./contributing/development/transferwise.md
  developers/post-donation-redirect: ./contributing/development/post-donation-redirect.md
  developers/custom-tweets: ./contributing/development/custom-tweets.md
  developers/manual-reporting: ./contributing/development/manual-reporting.md
  developers/github-permissions: ./contributing/development/github-permissions.md
  developers/translations: ./contributing/development/translations.md
  developers/testing-with-cypress: ./contributing/development/testing-with-cypress.md
  developers/collectives-locations: ./contributing/development/collectives-locations.md
  projects: ./internal/projects/README.md
  projects/maintainerati-berlin-2019: ./internal/projects/maintainerati-berlin-2019.md
  projects/season-of-docs-2019: ./internal/projects/season-of-docs-2019.md
  design: ./contributing/design/README.md
  design/understanding-the-design-workflow: ./contributing/design/understanding-the-design-workflow.md
  design/untitled: ./contributing/design/contribution-guidelines.md
  the-open-collective-way: ./internal/the-open-collective-way/README.md
  the-open-collective-way/community-guidelines: ./about/the-open-collective-way/community-guidelines.md
  the-open-collective-way/core-contributors-guidelines: ./about/the-open-collective-way/core-contributors-guidelines.md
  the-open-collective-way/core-contributors-communication: ./about/the-open-collective-way/core-contributors-communication.md
  the-open-collective-way/core-contributors-expenses: ./about/the-open-collective-way/core-contributors-expenses.md
  the-open-collective-way/core-contributors-leave: ./about/the-open-collective-way/core-contributors-leave.md
  the-open-collective-way/core-contributors-compensation: ./about/the-open-collective-way/core-contributors-compensation.md
